export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE = 'POPUP_CLOSE';
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_SIGNED_ASSESSEE_PERMISSION_SAGA = 'GET_SIGNED_ASSESSEE_PERMISSION_SAGA';
export const SET_USER = 'SET_USER';
export const SET_SIGN_IN_STATUS = 'SET_SIGN_IN_STATUS';
export const SET_USER_STATE = 'SET_USER_STATE';
export const SET_ASSESSEE_PERMISSION = 'SET_ASSESSEE_PERMISSION';
export const GET_ASSESSES_SAGA = 'GET_ASSESSES_SAGA';
export const ASSESSEE_SIGN_ON = 'ASSESSEE_SIGN_ON';
export const ASSESSEE_SIGN_IN_SAGA = 'ASSESSEE_SIGN_IN_SAGA';
export const SET_DISPLAY_PANE_FOUR_SHOW = 'SET_DISPLAY_PANE_FOUR_SHOW';
export const SET_GRID_COLUMN_COUNT_VALUE = 'SET_GRID_COLUMN_COUNT_VALUE';
export const SET_SECONDARY_OPTION_VALUE = 'SET_SECONDARY_OPTION_VALUE';
export const SET_SECONDARY_CREATE_OPTION_VALUE = 'SET_SECONDARY_CREATE_OPTION_VALUE';
export const SET_MOBILE_PANE_STATE = 'SET_MOBILE_PANE_STATE';
export const SET_SIGN_ON_SINGLE_STATE = 'SET_SIGN_ON_SINGLE_STATE';
export const CLEAR_SIGN_ON_SINGLE_STATE = 'CLEAR_SIGN_ON_SINGLE_STATE';
export const ASSOCIATE_SIGN_ON = 'ASSOCIATE_SIGN_ON';
export const SET_NEXT_POPUP = 'SET_NEXT_POPUP';
export const PREVIOUS_POPUP = 'PREVIOUS_POPUP';
export const SET_POPUP_STATE = 'SET_POPUP_STATE';
export const SET_MIDDLEPANE_SECONDARY_OPTION = 'SET_MIDDLEPANE_SECONDARY_OPTION';
export const SET_MIDDLEPANE_PREVIOUS_POPUP = 'SET_MIDDLEPANE_PREVIOUS_POPUP';
// set middle pane states
export const SET_MIDDLEPANE_STATE = 'SET_MIDDLEPANE_STATE';
export const SET_SELECTED_ASSOCIATE = 'SET_SELECTED_ASSOCIATE';
export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';
export const SET_PAGE_COUNT = 'SET_PAGE_COUNT';
export const SET_POPUP_VALUE = 'SET_POPUP_VALUE';
export const SET_SCAN_POPUP_STATE = 'SET_SCAN_POPUP_STATE';
export const CLEAR_POPUP_INFO = 'CLEAR_POPUP_INFO';
export const SET_POPUP_SINGLE_STATE = 'SET_POPUP_SINGLE_STATE';
// for assessee information
export const ASSESSEE_INFO_CREATE = 'ASSESSEE_INFO_CREATE';
export const ASSESSEE_CREATE = 'ASSESSEE_CREATE';
export const SET_DISPLAY_TWO_SINGLE_STATE = 'SET_DISPLAY_TWO_SINGLE_STATE';
export const SET_ASSESSEE_DYNAMIC_SINGLE_STATE = 'SET_ASSESSEE_DYNAMIC_SINGLE_STATE';
export const UPDATE_ASSESSEE_INFO = 'UPDATE_ASSESSEE_INFO';
export const UPDATE_ASSESSEE_BASIC_INFO = 'UPDATE_ASSESSEE_BASIC_INFO';
export const UPDATE_ASSESSEE_MOBILE_INFO = 'UPDATE_ASSESSEE_MOBILE_INFO';
export const UPDATE_ASSESSEE_PERSONAL_INFO = 'UPDATE_ASSESSEE_PERSONAL_INFO';
export const UPDATE_ASSESSEE_HOMEADDRESS_INFO = 'UPDATE_ASSESSEE_HOMEADDRESS_INFO';
export const UPDATE_ASSESSEE_ADDRESS_EMAIL_PRIMARY_INFO =
  'UPDATE_ASSESSEE_ADDRESS_EMAIL_PRIMARY_INFO';
export const UPDATE_ASSESSEE_ADDRESS_EMAIL_SECONDARY_INFO =
  'UPDATE_ASSESSEE_ADDRESS_EMAIL_SECONDARY_INFO';
export const UPDATE_ASSESSEE_SETUP_PRIMARY_INFO = 'UPDATE_ASSESSEE_SETUP_PRIMARY_INFO';
export const UPDATE_ASSESSEE_ENGAGEMENT_INFO = 'UPDATE_ASSESSEE_ENGAGEMENT_INFO';
export const CLEAR_ASSESSEE_INFO = 'CLEAR_ASSESSEE_INFO';
export const UPDATE_ASSESSEE_COMMUNICATION = 'UPDATE_ASSESSEE_COMMUNICATION';
export const SET_ASSESSEE_INFORMATION_DATA = 'SET_ASSESSEE_INFORMATION_DATA';
export const REVIEWLIST_DISTINCT_DATA = 'REVIEWLIST_DISTINCT_DATA';
export const SET_REQUEST_OBJECT = 'SET_REQUEST_OBJECT';
export const SET_CORE_REVIEW_LIST_DATA = 'SET_CORE_REVIEW_LIST_DATA';
export const SET_CORE_REVIEW_LIST_REQ_DATA = 'SET_CORE_REVIEW_LIST_REQ_DATA';
export const SET_ASSESSEE_ROLE_REDUCER_STATE = 'SET_ASSESSEE_ROLE_REDUCER_STATE';
export const SET_ASSOCIATE_ROLE_REDUCER_STATE = 'SET_ASSOCIATE_ROLE_REDUCER_STATE';
export const CLEAR_ROLE_REDUCER_STATE = 'CLEAR_ROLE_REDUCER_STATE';
export const SET_GROUP_REDUCER_STATE = 'SET_GROUP_REDUCER_STATE';
export const CLEAR_GROUP_REDUCER_STATE = 'CLEAR_GROUP_REDUCER_STATE';
export const CLEAR_TYPE_REDUCER_STATE = 'CLEAR_TYPE_REDUCER_STATE';
export const SET_TYPE_REDUCER_STATE = 'SET_TYPE_REDUCER_STATE';
//for assessments SAGA
export const GET_ASSESSMENT_GROUP_REVIEW_LIST_SAGA = 'GET_ASSESSMENT_GROUP_REVIEW_LIST_SAGA';
export const GET_ASSESSMENT_TYPE_REVIEW_LIST_SAGA = 'GET_ASSESSMENT_TYPE_REVIEW_LIST_SAGA';
export const ASSESSMENT_REVIEW_DISTINCT_SAGA = 'ASSESSMENT_REVIEW_DISTINCT_SAGA';
export const CREATE_ASSESSMENT_SAGA = 'CREATE_ASSESSMENT_SAGA';
//for assignments SAGA
export const GET_ASSIGNMENT_GROUP_REVIEW_LIST_SAGA = 'GET_ASSIGNMENT_GROUP_REVIEW_LIST_SAGA';
export const GET_ASSIGNMENT_TYPE_REVIEW_LIST_SAGA = 'GET_ASSIGNMENT_TYPE_REVIEW_LIST_SAGA';
export const ASSIGNMENT_REVIEW_DISTINCT_SAGA = 'ASSIGNMENT_REVIEW_DISTINCT_SAGA';
export const CREATE_ASSIGNMENT_SAGA = 'CREATE_ASSIGNMENT_SAGA';
//for assesees SAGA
export const GET_ASSESSEE_ROLE_REVIEW_LIST_SAGA = 'GET_ASSESSEE_ROLE_REVIEW_LIST_SAGA';
export const GET_ASSESSEE_GROUP_REVIEW_LIST_SAGA = 'GET_ASSESSEE_GROUP_REVIEW_LIST_SAGA';
export const GET_ASSESSEE_ROLE_REVIEW_INFO_SAGA = 'GET_ASSESSEE_ROLE_REVIEW_INFO_SAGA';
export const GET_ASSOCIATE_ROLE_REVIEW_INFO_SAGA = 'GET_ASSOCIATE_ROLE_REVIEW_INFO_SAGA';
export const CREATE_ASSESSEE_SAGA = 'CREATE_ASSESSEE_SAGA';
export const CREATE_ASSESSEE_ROLE_SAGA = 'CREATE_ASSESSEE_ROLE_SAGA';
export const ASSESSEE_REVIEW_DISTINCT_SAGA = 'ASSESSEE_REVIEW_DISTINCT_SAGA';
export const CREATE_GROUP_SAGA = 'CREATE_GROUP_SAGA';
export const CREATE_TYPE_SAGA = 'CREATE_TYPE_SAGA';
export const ASSESSEE_CONFIRM_SAGA = 'ASSESSEE_CONFIRM_SAGA';
// associates SAGA
export const CREATE_ASSOCIATE_SAGA = 'CREATE_ASSOCIATE_SAGA'; //create associate
export const ASSOCIATE_REVIEW_DISTINCT_SAGA = 'ASSOCIATE_REVIEW_DISTINCT_SAGA';
export const CREATE_ASSOCIATE_ROLE_SAGA = 'CREATE_ASSOCIATE_ROLE_SAGA';
export const GET_ASSOCIATE_ROLE_REVIEW_LIST_SAGA = 'GET_ASSOCIATE_ROLE_REVIEW_LIST_SAGA';
export const GET_ASSOCIATE_GROUP_REVIEW_LIST_SAGA = 'GET_ASSOCIATE_GROUP_REVIEW_LIST_SAGA';


//for assocaite information
export const UPDATE_ASSOCIATE_INFO = 'UPDATE_ASSOCIATE_INFO';
export const UPDATE_ASSOCIATE_WORKADDRESS_INFO = 'UPDATE_ASSOCIATE_WORKADDRESS_INFO';
export const UPDATE_ASSOCIATE_WORKTELEPHONE_INFO = 'UPDATE_ASSOCIATE_WORKTELEPHONE_INFO';
export const UPDATE_ASSOCIATE_BASIC_INFO = 'UPDATE_ASSOCIATE_BASIC_INFO';
export const UPDATE_ASSOCIATE_ADMIN_BASIC_INFO = 'UPDATE_ASSOCIATE_ADMIN_BASIC_INFO';
export const UPDATE_ASSOCIATE_ADMIN_MOBILE_INFO = 'UPDATE_ASSOCIATE_ADMIN_MOBILE_INFO';
export const UPDATE_ASSOCIATE_ADMIN_PERSONAL_INFO = 'UPDATE_ASSOCIATE_ADMIN_PERSONAL_INFO';
export const CLEAR_ASSOCIATE_INFO = 'CLEAR_ASSOCIATE_INFO';
export const ASSOCIATE_CREATE_INFO = 'ASSOCIATE_CREATE_INFO';
export const SET_ASSOCIATE_INFORMATION = 'SET_ASSOCIATE_INFORMATION'; //create associate
//VARIABLES FOR CORE POPUP
export const NAMEPOPUP = 'NAMEPOPUP';
export const NAMEALIASPOPUP = 'NAMEALIASPOPUP';
export const ALIASPOPUP = 'ALIASPOPUP';
export const PICTUREPOPUP = 'PICTUREPOPUP';
export const MOBILETELEPHONEPOPUP = 'MOBILETELEPHONEPOPUP';
export const ASSOCIATEPICTUREPOPUP = 'ASSOCIATEPICTUREPOPUP';
export const EMAILPOPUP = 'EMAILPOPUP';
export const SINGLEDROPDOWNPOPUP = 'SINGLEDROPDOWNPOPUP';
export const HOMEADDRESSPOPUP = 'HOMEADDRESSPOPUP';
export const WORKADDRESSPOPUP = 'WORKADDRESSPOPUP';
export const CONFIRMATIONPOPUP = 'CONFIRMATIONPOPUP';
export const ASSOCIATECONFIRMATIONPOPUP = 'ASSOCIATECONFIRMATIONPOPUP';
export const DESCRIPTIONPOPUP = 'DESCRIPTIONPOPUP';
export const WORKTELEPHONE = 'WORKTELEPHONE';
export const ROLEPOPUP = 'ROLEPOPUP';
//for footer icon in middle pane
export const FILTERMODE = 'FILTERMODE';
export const NAVIGATOR_MODE = 'NAVIGATOR_MODE';
export const FILTERMODE_ENABLE = 'FILTERMODE_ENABLE';

// Assessees Module
export const ASSESSEE_POPUP_OPEN = 'ASSESSEE_POPUP_OPEN';
export const ASSESSEE_POPUP_CLOSE = 'ASSESSEE_POPUP_CLOSE';
export const SET_ASSESSEE_NEXT_POPUP = 'SET_ASSESSEE_NEXT_POPUP';
export const SET_ASSESSEE_PREVIOUS_POPUP = 'SET_ASSESSEE_PREVIOUS_POPUP';
export const SET_ASSESSEE_SECONDARY_OPTION_VALUE = 'SET_ASSESSEE_SECONDARY_OPTION_VALUE';
export const SET_ASSESSEE_SECONDARY_POPUP = 'SET_ASSESSEE_SECONDARY_POPUP';
export const GET_ASSESSEE_GROUP_REVIEW_INFO_SAGA = 'GET_ASSESSEE_GROUP_REVIEW_INFO_SAGA';

// Associates Module
export const ASSOCIATE_POPUP_OPEN = 'ASSOCIATE_POPUP_OPEN';
export const ASSOCIATE_POPUP_CLOSE = 'ASSOCIATE_POPUP_CLOSE';
export const SET_ASSOCIATE_NEXT_POPUP = 'SET_ASSOCIATE_NEXT_POPUP';
export const SET_ASSOCIATE_SECONDARY_POPUP = 'SET_ASSOCIATE_SECONDARY_POPUP';
export const SET_ASSOCIATE_PREVIOUS_POPUP = 'SET_ASSOCIATE_PREVIOUS_POPUP';
export const SET_ASSOCIATE_SECONDARY_OPTION_VALUE = 'SET_ASSOCIATE_SECONDARY_OPTION_VALUE';
export const GET_ASSOCIATE_GROUP_REVIEW_INFO_SAGA = 'GET_ASSOCIATE_GROUP_REVIEW_INFO_SAGA';

// Assessment Module
export const ASSESSMENT_POPUP_OPEN = 'ASSESSMENT_POPUP_OPEN';
export const ASSESSMENT_POPUP_CLOSE = 'ASSESSMENT_POPUP_CLOSE';
export const SET_ASSESSMENT_NEXT_POPUP = 'SET_ASSESSMENT_NEXT_POPUP';
export const SET_ASSESSMENT_PREVIOUS_POPUP = 'SET_ASSESSMENT_PREVIOUS_POPUP';
export const CLEAR_ASSESSMENT_INFO = 'CLEAR_ASSESSMENT_INFO';
export const SET_ASSESSMENT_SECONDARY_OPTION_VALUE = 'SET_ASSESSMENT_SECONDARY_OPTION_VALUE';
export const SET_ASSESSMENT_SECONDARY_POPUP = 'SET_ASSESSMENT_SECONDARY_POPUP';
export const GET_ASSESSMENT_GROUP_REVIEW_INFO_SAGA = 'GET_ASSESSMENT_GROUP_REVIEW_INFO_SAGA';
export const GET_ASSESSMENT_TYPE_REVIEW_INFO_SAGA = 'GET_ASSESSMENT_TYPE_REVIEW_INFO_SAGA';
export const GET_ASSESSMENT_INFO_SAGA = 'GET_ASSESSMENT_INFO_SAGA';
export const SET_ASSESSMENT_REDUCER_STATE = 'SET_ASSESSMENT_REDUCER_STATE';
export const SET_ASSESSMENT_BASIC_REDUCER_STATE = 'SET_ASSESSMENT_BASIC_REDUCER_STATE';

// Assignments Module
export const ASSIGNMENT_POPUP_OPEN = 'ASSIGNMENT_POPUP_OPEN';
export const ASSIGNMENT_POPUP_CLOSE = 'ASSIGNMENT_POPUP_CLOSE';
export const SET_ASSIGNMENT_NEXT_POPUP = 'SET_ASSIGNMENT_NEXT_POPUP';
export const SET_ASSIGNMENT_PREVIOUS_POPUP = 'SET_ASSIGNMENT_PREVIOUS_POPUP';
export const CLEAR_ASSIGNMENT_INFO = 'CLEAR_ASSIGNMENT_INFO';
export const SET_ASSIGNMENT_SECONDARY_POPUP = 'SET_ASSIGNMENT_SECONDARY_POPUP';
export const SET_ASSIGNMENT_SECONDARY_OPTION_VALUE = 'SET_ASSIGNMENT_SECONDARY_OPTION_VALUE';
export const GET_ASSIGNMENT_GROUP_REVIEW_INFO_SAGA = 'GET_ASSIGNMENT_GROUP_REVIEW_INFO_SAGA';
export const GET_ASSIGNMENT_TYPE_REVIEW_INFO_SAGA = 'GET_ASSIGNMENT_TYPE_REVIEW_INFO_SAGA';
export const SET_ASSIGNMENT_BASIC_REDUCER_STATE = 'SET_ASSIGNMENT_BASIC_REDUCER_STATE';
export const GET_ASSIGNMENT_INFO_SAGA = 'GET_ASSIGNMENT_INFO_SAGA';

// Section PopUps
export const SECTION_POPUP_OPEN = 'SECTION_POPUP_OPEN';
export const SET_SECTION_HEADER_ONE = 'SET_SECTION_HEADER_ONE';
export const SET_SECTION_HEADER_ONE_BADGE_ONE = 'SET_SECTION_HEADER_ONE_BADGE_ONE';
export const SET_SECTION_TWO_SECONDARY_OPTION_VALUE = 'SET_SECTION_TWO_SECONDARY_OPTION_VALUE';
export const CLEAR_IGAUGE_REDUCER = 'CLEAR_IGAUGE_REDUCER';
export const SECTION_POPUP_CLOSE = 'SECTION_POPUP_CLOSE';
export const SET_PREVIOUS_SECTION_POPUP = 'SET_PREVIOUS_SECTION_POPUP';

// displayPaneThree
export const SET_DISPLAY_PANE_THREE_STATE = 'SET_DISPLAY_PANE_THREE_STATE';
export const GET_ASSESSEE_INFO_SAGA = 'GET_ASSESSEE_INFO_SAGA';
export const CLEAR_DISPLAY_PANE_THREE = 'CLEAR_DISPLAY_PANE_THREE';
export const GET_ASSOCIATE_INFO_SAGA = 'GET_ASSOCIATE_INFO_SAGA';
export const SET_DISPLAY_PANE_THREE_REVIEW_MODE = 'SET_DISPLAY_PANE_THREE_REVIEW_MODE';
